import torch

args = {
    "aspect_ratio_thresh": 1.6,
    "camid": 0,
    "max_box_area": 80000,
    "ckpt": "bytetrack/pretrained/yolox_m_custom.pth",
    "conf": None,
    "device": "cuda" if torch.cuda.is_available() else "cpu",
    "exp_file": 'bytetrack/exps/example/mot/yolox_m_mix_det.py',
    "experiment_name": 'yolox_m_mix_det',
    "fp16": False,
    "fps": 30,
    "fuse": True,
    "match_thresh": 0.8,
    "min_box_area": 10,
    "mot20": False,
    "name": None,
    "nms": None,

    "path": 'video_demo/test.avi',
    "demo": 'video',


    # "demo": "image",
    # "path": "image_demo/",

    "save_result": True,
    "track_buffer": 30,
    "track_thresh": 0.5,
    "trt": False,
    "tsize": None,
}

labels = {
    1: "ball",
    2 : "referee",
    3 : "player",
    4 : "goalkeeper"
}

# labels = {
#     1: "person",
#     2: "bicycle",
#     3: "car",
#     4: "motorbike",
#     5: "aeroplane",
#     6: "bus",
#     7: "train",
#     8: "truck",
#     9: "boat",
#     10: "traffic light",
#     11: "fire hydrant",
#     12: "stop sign",
#     13: "parking meter",
#     14: "bench",
#     15: "bird",
#     16: "cat",
#     17: "dog",
#     18: "horse",
#     19: "sheep",
#     20: "cow",
#     21: "elephant",
#     22: "bear",
#     23: "zebra",
#     24: "giraffe",
#     25: "backpack",
#     26: "umbrella",
#     27: "handbag",
#     28: "tie",
#     29: "suitcase",
#     30: "frisbee",
#     31: "skis",
#     32: "snowboard",
#     33: "sports ball",
#     34: "kite",
#     35: "baseball bat",
#     36: "baseball glove",
#     37: "skateboard",
#     38: "surfboard",
#     39: "tennis racket",
#     40: "bottle",
#     41: "wine glass",
#     42: "cup",
#     43: "fork",
#     44: "knife",
#     45: "spoon",
#     46: "bowl",
#     47: "banana",
#     48: "apple",
#     49: "sandwich",
#     50: "orange",
#     51: "broccoli",
#     52: "carrot",
#     53: "hot dog",
#     54: "pizza",
#     55: "donut",
#     56: "cake",
#     57: "chair",
#     58: "sofa",
#     59: "pottedplant",
#     60: "bed",
#     61: "diningtable",
#     62: "toilet",
#     63: "tvmonitor",
#     64: "laptop",
#     65: "mouse",
#     66: "remote",
#     67: "keyboard",
#     68: "cell phone",
#     69: "microwave",
#     70: "oven",
#     71: "toaster",
#     72: "sink",
#     73: "refrigerator",
#     74: "book",
#     75: "clock",
#     76: "vase",
#     77: "scissors",
#     78: "teddy bear",
#     79: "hair drier",
#     80: "toothbrush",
# }
